config/routes.rb
Rails.application.routes.draw do
  get 'good/index'

  get 'good/show'

  get 'good/ask' => 'good#ask'

  get 'good/form'

  get 'good/search'

  post 'good/search' => 'good#findout'

  root 'main#index'

  get 'main/index'
  get 'main/camera'
  get 'main/rent'
  get 'main/return'
  get 'main/register'
  get 'main/register_save'

  get 'user/index' => 'user#index'

  get 'user/favorite' => 'user#favorite'
  devise_for :users

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :good
end

app/models/good.rb
class Good < ActiveRecord::Base
  belongs_to :user

  def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      @goods = Good.where(['goods_name LIKE ?', "%#{search}%"])
    else
      @goods = Good.all #全て表示。
    end
  end
end

app/models/rent.rb
class Rent < ActiveRecord::Base
  belongs_to :user
  belongs_to :good
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :good
  has_many :rent
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!, :except => []

  layout :layout_by_resource

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_name, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :user_name, :email, :password, :remember_me) }
    end

  private
    def layout_by_resource
      if devise_controller?
        "authentication"
      else
        "application"
      end
    end
end

app/controllers/good_controller.rb
class GoodController < ApplicationController
  def index
    @goods = Good.search(params[:search])
  end

  def show
    @good = Good.find_by(id:params[:good_id])
    @rent = Rent.where(good_id: @good.id, :return_date => nil).last

    if @rent.present?
      @good_status = "貸し出し中です。リマインドしますか。";
      @good_status_params = 1
    else
      @good_status = "今借りる";
      @good_status_params = 2
    end
  end

  def ask
    good_status = params[:good_status]
    # good_status == 1 : remiind
    # good_status == 2 : rent soon
    if good_status == "1"
      if Favorite.find_by(user_id:current_user.id,good_id: params[:good_id]).present?
        flash[:notice] = "You already registered!"
      else
        remind = Favorite.create(user_id:current_user.id,good_id: params[:good_id])
          flash[:notice] = "Successed!Will remind you!"  if remind.valid?
      end

      redirect_to({:controller => 'user', :action=>'favorite' })
    else
      if Rent.find_by(user_id:current_user.id, good_id: params[:good_id]).present?
          flash[:notice] = "You rent already!"
      else
        if rent = Rent.create(user_id: current_user.id ,good_id: params[:good_id], expire_start_date: Time.now, expire_end_date:Time.now + 14.days )
          flash[:notice] = "Successed!You rented now!"
        end
      end
      redirect_to({:controller => 'user', :action=>'index' })
    end

  end

  def form
  end

  def search
  end
    helper_method :current_user

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end

  def camera
    @from = params[:from]
  end

  def rent
    if params[:good_id].present?
      good = Good.find(params[:good_id])

      expire_end_date = params[:return_date]

      if Rent.where(:user_id => current_user.id, :good_id => good.id, :return_date => nil ).present?
        @save_success = 1
      else
        @save_success = 2
        Rent.create(:user_id => current_user.id, :good_id => good.id, :expire_start_date => Time.now, :expire_end_date => expire_end_date)
      end
    else
      if params[:barcode].present?
        @barcode = params[:barcode]

        @good = Good.where(barcode: @barcode).first
      end
    end
  end

  def return
    if params[:barcode].present?
      barcode = params[:barcode]

      @good = Good.where(barcode: barcode).first

      if @good.present?
        @rents = Rent.where(:user_id => current_user.id, :good_id => @good.id)

        @rents.each do |rent|
          Rent.update(rent.id, :return_date => Time.now)
        end
      end
    end
  end

  def register
    if params[:barcode].present?
      barcode = params[:barcode]

      response = RestClient::Request.execute(
        method: :get,
        url: 'https://www.googleapis.com/books/v1/volumes?q=isbn:' + barcode
      )

      json = JSON.parse(response)

      if json["items"].present?
        @title = json["items"][0]["volumeInfo"]["title"]
        @description = json["items"][0]["volumeInfo"]["description"]
        @imglink = json["items"][0]["volumeInfo"]["imageLinks"]["thumbnail"]

        session[:title] = @title
        session[:barcode] = barcode
        session[:description] = @description
        session[:imglink] = @imglink
      end
    end
  end

  def register_save
    title = session[:title]
    barcode = session[:barcode]
    description = session[:description]
    imglink = session[:imglink]

    if Good.where(:barcode => barcode).present?
      @exist = true
    else
      Good::create(:goods_name => title, :barcode => barcode, :description => description, :user_id => current_user.id, :link => imglink)
      @save = true
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @current_user ||= User.find_by(id: session[:id])
    @rents = Rent.where(user_id: current_user.id, :return_date => nil)
    @goods = Good.where(user_id: current_user.id)
  end

    def favorite
      @current_user ||= User.find_by(id: current_user.id)
      @favorites = Favorite.where(user_id: current_user.id)
    end
    helper_method :current_user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/good_helper.rb
module GoodHelper
  def username(user_id)
    name = User.find_by(id: user_id).user_name
    return name
  end

  def confirm_good_status(good_id)
    good_status_confirm = Rent.where(good_id: good_id, :return_date => nil).last
    if good_status_confirm.present?
       return "Someone use!"
     else
       return "You can rent NOW!"
    end
  end

  def rent_user_name(good_id)
    rent = Rent.where(good_id: good_id).last
    if rent.present? && rent.user.present?
      rent.user.user_name
    else
      'なし'
    end
  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
  def confirm_good_status(good_id)
    good_status_confirm = Rent.where(good_id: good_id, :return_date => nil).last
    if good_status_confirm.present?
       return "Someone use!"
     else
       return "You can rent NOW!"
    end
  end

  def username(user_id)
    name = User.find_by(id: user_id).user_name
    return name
  end

  def rent_user_name(good_id)
    rent = Rent.where(good_id: good_id).last
    if rent.present? && rent.user.present?
      rent.user.user_name
    else
      'なし'
    end
  end
end

app/views/good/form.html.erb
<h1>Good#form</h1>
<p>Find me in app/views/good/form.html.erb</p>

app/views/good/index.html.erb
<div class="card">
  <div class="header">
      <h2>検索</h2>
  </div>
  <div class="body">
    <%= form_tag good_index_path, :method => 'get' do %>
    <div class="row clearfix">
        <div class="col-sm-12">
        <div class="form-group">
          <div class="form-line">
              <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "キーワードご入力" %>
          </div>
        </div>
        <div class="input-group">
          <%= button_tag type: "submit", :name => nil, class: 'btn btn-default', style: 'width: 100%;' do %>
            <i class="material-icons">search</i>検索
          <% end %>
        </div>
        </div><!-- /.col-sm-12 -->
      </div><!-- /.row -->
    <% end %>
  </div>
</div>

<div class="container-fluid">
  <div class="block-header">
      <h2>貸し出し備品一覧</h2>
  </div>
</div>

<% @goods.each do |good| %><br>
  <div class="card">
    <div class="header">
        <h2>
            <b><%= good.goods_name %></B>
        </h2>
        <small>借り手：<%= rent_user_name(good.id) %></small></br>
        <small>登録者:<%= good.user.user_name if good.user.present?%></small></br>
        <small><%= flash[:notice] if flash[:notice]%></small>
    </div>
    <div class="body">
      <div class="row clearfix">
          <div class="col-sm-12">
            <%= good.description[0..30] + '...' %>
            <%= link_to "詳細確認", controller: "good", action: "show", good_id: good.id %>
          </div><!-- /.col-sm-12 -->
      </div><!-- /.row -->
    </div>
  </div>
<% end %>

app/views/good/show.html.erb
<div class="card">
  <div class="header">
      <h2>
          <b><%= @good.goods_name %></b>
      </h2>
      <small>barcode: <%= @good.barcode %></small><br/>
      <small>レンタル人:
        <% if @rent.present? && @rent.user.present?%>
          <%= @rent.user.user_name %>
        <% else %>
          <%= 'なし' %>
        <% end %><br/>
        <% if !@rent.present? %>
          <%= link_to @good_status, {controller: "good", action: "ask", good_status:@good_status_params, good_id: @good.id, user_id: current_user.id} %>
        <% else @rent.user.id != current_user.id %>
          <%= link_to @good_status, {controller: "good", action: "ask", good_status:@good_status_params, good_id: @good.id, user_id: current_user.id} %>
        <% end %>
      </small>
  </div>
  <div class="body">
    <div class="row clearfix">
        <div class="col-sm-12">
          <div class="thumbnail">
              <img src="<%= @good.link %>">
              <div class="caption">
                  <%= @good.description %>
              </div>
          </div>
        </div><!-- /.col-sm-12 -->
    </div><!-- /.row -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <title>Kashidashichan</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Favicon-->
    <link rel="icon" href="favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
</head>
<%= flash[:notice] if flash[:notice]%>
<body class="theme-red">
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->
    <!-- Search Bar -->
    <div class="search-bar">
        <div class="search-icon">
            <i class="material-icons">search</i>
        </div>
        <input type="text" placeholder="START TYPING...">
        <div class="close-search">
            <i class="material-icons">close</i>
        </div>
    </div>
    <!-- #END# Search Bar -->
    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
              <a href="/" class="a-home">
                  <i class="material-icons">home</i>
              </a>
              <a href="javascript:void(0);" class="bars"></a>
              <a class="navbar-brand" href="/">かしだしちゃん〜</a>
            </div>
        </div>
    </nav>
    <!-- #Top Bar -->
    <section>
        <!-- Left Sidebar -->
        <aside id="leftsidebar" class="sidebar">
            <!-- User Info -->
            <div class="user-info">
                <div class="image">
                  <%= image_tag "user.png", style: "width: 48px; height: 48px;" %>
                </div>
                <div class="info-container">
                    <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.user_name %></div>
                    <div class="email"><%= current_user.email %></div>
                    <div class="btn-group user-helper-dropdown">
                        <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                        <ul class="dropdown-menu pull-right">
                            <% if user_signed_in? %>
                              <li>
                                <%= link_to(destroy_user_session_path, method: :delete) do %>
                                  <i class="material-icons">input</i>ログアウト
                                <% end %>
                              </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- #User Info -->
            <!-- Menu -->
            <div class="menu">
                <ul class="list">
                    <li class="header">MAIN NAVIGATION</li>
                    <li class="active">
                        <a href="/">
                            <i class="material-icons">home</i>
                            <span>Home</span>
                        </a>
                    </li>
                    <li>
                        <a href="<%= url_for(controller: 'user', action: 'index') %>">
                            <i class="material-icons">view_list</i>
                            <span>貸し出し一覧</span>
                        </a>
                    </li>
                    <li>
                        <a href="<%= url_for(controller: 'user', action: 'favorite') %>">
                            <i class="material-icons">favorite</i>
                            <span>お気に入り一覧</span>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- #Menu -->
            <!-- Footer -->
            <div class="legal">
                <div class="copyright">
                    &copy; 2016 - 2017 <a href="javascript:void(0);">スーパサイヤチーム</a>.
                </div>
                <div class="version">
                    <b>Version: </b> 1.0.0
                </div>
            </div>
            <!-- #Footer -->
        </aside>
        <!-- #END# Left Sidebar -->

    </section>

    <section class="content">
        <%= yield %>
    </section>
</body>

</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <title>Kashidashichan</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Favicon-->
    <link rel="icon" href="favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
</head>
<body class="login-page">
    <%= yield %>
</body>

</html>

app/views/main/camera.html.erb
<div class="container-fluid">
    <div class="block-header">
        <h2>バーコードスキャン</h2>
    </div>
  <div class="card">
    <div class="header">
        <h2>
            バーコード
        </h2>
    </div>
    <div class="body">
      <div class="row clearfix">
          <div class="col-sm-12">
          <div class="form-group">
            <div class="form-line">
                <input id="scanner_input" class="form-control" placeholder="下記のボタンをクリックして、バーコードをスキャンできる" type="text" />
            </div>
          </div>

          <div class="input-group">
            <label class="btn btn-default" style="width: 100%;">
                <i class="material-icons">camera_enhance</i> カメラ利用
                <input type="file" accept="image/*;capture=camera" capture="camera" class="hidden" />
            </label>
          </div>
          </div><!-- /.col-sm-12 -->
      </div><!-- /.row -->
    </div>
  </div>
</div>

<script type="text/javascript">
$(function() {
    // Create the QuaggaJS config object for the live stream
    var liveStreamConfig = {
            inputStream: {
                type : "LiveStream",
                constraints: {
                    width: {min: 640},
                    height: {min: 480},
                    aspectRatio: {min: 1, max: 100},
                    facingMode: "environment" // or "user" for the front camera
                }
            },
            locator: {
                patchSize: "medium",
                halfSample: true
            },
            numOfWorkers: (navigator.hardwareConcurrency ? navigator.hardwareConcurrency : 4),
            decoder: {
                "readers":[
                    {"format":"ean_reader","config":{}}
                ]
            },
            locate: true
        };
    // The fallback to the file API requires a different inputStream option.
    // The rest is the same
    var fileConfig = $.extend(
            {},
            liveStreamConfig,
            {
                inputStream: {
                    size: 800
                }
            }
        );

    // the barcode had actually been found.
    Quagga.onDetected(function(result) {
        if (result.codeResult.code){
            $('#scanner_input').val(result.codeResult.code);
            Quagga.stop();
            setTimeout(function(){ $('#livestream_scanner').modal('hide'); }, 1000);
        }
    });

    // Call Quagga.decodeSingle() for every file selected in the
    // file input
    $("input:file").on("change", function(e) {
        if (e.target.files && e.target.files.length) {
            Quagga.decodeSingle($.extend({}, fileConfig, {src: URL.createObjectURL(e.target.files[0])}), function(result) {
              // alert(result.codeResult.code);
              var from = "<%= @from %>";
              switch (from) {
                case "rent":
                  window.location.replace("/main/rent?barcode=" + result.codeResult.code);
                  break;
                case "return":
                  window.location.replace("/main/return?barcode=" + result.codeResult.code);
                  break;
                case "register":
                  window.location.replace("/main/register?barcode=" + result.codeResult.code);
                  break;
              }
            });
        }
    });
});
</script>

app/views/main/index.html.erb
<div class="container-fluid">
    <!-- Widgets -->
    <div class="row clearfix">
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
          <div class="info-box bg-orange">
              <div class="icon">
                  <i class="material-icons">find_in_page</i>
              </div>
              <div class="content">
                  <h2><%= link_to "検索", {controller: "good", action: "index"} %></h2>
              </div>
          </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
          <div class="info-box bg-cyan">
              <div class="icon">
                  <i class="material-icons">add_circle</i>
              </div>
              <div class="content">
                  <h2><%= link_to "貸し出し", {controller: "main", action: "camera", :from => 'rent'} %></h2>
              </div>
          </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
          <div class="info-box bg-light-green">
              <div class="icon">
                  <i class="material-icons">backspace</i>
              </div>
              <div class="content">
                  <h2><%= link_to "返し", {controller: "main", action: "camera", :from => 'return'} %></h2>
              </div>
          </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
          <div class="info-box bg-pink">
              <div class="icon">
                  <i class="material-icons">camera_enhance</i>
              </div>
              <div class="content">
                  <h2><%= link_to "登録", {controller: "main", action: "camera", :from => 'register'} %></h2>
              </div>
          </div>
        </div>
    </div>
    <!-- #END# Widgets -->
</div>

app/views/main/register.html.erb
<% if @title.present? %>
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
          <div class="header">
              <h2>
                  <%= @title %>
              </h2>
          </div>
          <div class="body">
              <div class="row" style="padding-bottom: 0px;">
                  <div class="col-sm-12">
                      <div class="thumbnail">
                          <img src="<%= @imglink %>">
                          <div class="caption">
                              <%= @description %>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="row">
                  <div class="col-sm-12"　style="margin-bottom: 0px !important;">
                      <div class="input-group">
                        <%= form_tag main_register_save_path, :method => 'get' do %>
                          <%= button_tag type: "submit", :name => nil, class: 'btn btn-primary', style: 'width: 100%;' do %>
                            <i class="material-icons">add</i>登録
                          <% end %>
                        <% end %>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
<% else %>
<div class="card">
  <div class="body">
    <div class="row clearfix">
        <div class="col-sm-12">
            バーコードに対する本が存在していないです。
        </div><!-- /.col-sm-12 -->
    </div><!-- /.row -->
  </div>
</div>
<% end %>

app/views/main/register_save.html.erb
<div class="card">
  <div class="body">
    <div class="row clearfix">
        <div class="col-sm-12">
          <% if @exist.present? %>
            このバーコードに関する備品がすでに登録されました。
          <% else %>
            備品登録できました。
          <% end %>
        </div><!-- /.col-sm-12 -->
    </div><!-- /.row -->
  </div>
</div>

app/views/main/rent.html.erb
<% if @save_success.present? %>
<div class="card">
  <div class="body">
    <div class="row clearfix">
        <div class="col-sm-12">
          <% if @save_success == 1 %>
            すでに貸し出し登録しました。
          <% else %>
            貸し出し登録できました。
          <% end %>
        </div><!-- /.col-sm-12 -->
    </div><!-- /.row -->
  </div>
</div>
<% elsif @good.present? %>
<div class="container-fluid">
  <div class="block-header">
      <h2>貸し出しもの情報</h2>
  </div>
  <div class="card">
    <div class="header">
        <h2>
            <b><%= @good.goods_name %></B>
        </h2>
        <small>barcode: <%= @good.barcode %></small>
    </div>
    <div class="body">
      <div class="row clearfix">
          <div class="col-sm-12">
            <div class="thumbnail">
                <img src="<%= @good.link %>">
                <div class="caption">
                    <%= @good.description %>
                </div>
            </div>
          </div><!-- /.col-sm-12 -->
      </div><!-- /.row -->
    </div>
  </div>

  <div class="card">
    <div class="header">
        <h2>
            <b>貸し出し情報ご記入</B>
        </h2>
    </div>
    <div class="body" style="padding-bottom: 0px;">
      <%= form_tag('/main/rent', method: :get) do %>
      <div class="row clearfix">
        <div class="col-sm-12">
          <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <div class="form-line">
                      <input type="hidden" name="good_id" value="<%= @good.id %>" >
                        <input type="text" name="return_date" class="datepicker form-control" placeholder="返す予定日を選んでください！">
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
              <button type="submit" class="btn btn-primary" style="width: 100%; height: 50px;">貸し出し</button>
            </div>
          </div>
        </div><!-- /.col-sm-12 -->
      </div><!-- /.row -->
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
$(function () {
    $('.datepicker').bootstrapMaterialDatePicker({
        format: 'dddd DD MMMM YYYY',
        minDate: moment(),
        clearButton: true,
        weekStart: 1,
        time: false
    });
});
</script>
<% else %>
<div class="card">
  <div class="body">
    <div class="row clearfix">
        <div class="col-sm-12">
            バーコードが存在していないです。
        </div><!-- /.col-sm-12 -->
    </div><!-- /.row -->
  </div>
</div>
<% end %>

app/views/main/return.html.erb
<div class="card">
  <div class="body">
    <div class="row clearfix">
        <div class="col-sm-12">
          <% if @good.present? %>
            返却手続き完了です。
          <% else %>
            バーコードが存在していないです。
          <% end %>
        </div><!-- /.col-sm-12 -->
    </div><!-- /.row -->
  </div>
</div>

app/views/user/favorite.html.erb
<div class="container-fluid">
  <div class="row clearfix">
    <!-- Task Info -->
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
        <div class="card">
            <div class="header">
                <h2>お気に入り一覧</h2>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-hover dashboard-task-infos">
                        <thead>
                            <tr>
                              <th>備品名</th>
                              <th>借り手</th>
                              <th>詳細</th>
                            </tr>
                        </thead>
                        <tbody>
                          <% @favorites.each do |f| %>
                            <tr>
                                <td><%= f.good.goods_name %></td>
                                <td><%= rent_user_name(f.good_id)%></td>
                                <td>
                                  <%= link_to "詳細", controller: "good", action: "show", good_id: f.good.id %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Task Info -->
</div>

app/views/user/index.html.erb
<div class="container-fluid">
  <div class="row clearfix">
    <!-- Task Info -->
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
        <div class="card">
            <div class="header">
                <h2>貸出一覧</h2>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-hover dashboard-task-infos">
                        <thead>
                            <tr>
                                <th>備品名</th>
                                <th>残り</th>
                            </tr>
                        </thead>
                        <tbody>
                          <% @rents.each do |rent| %>
                            <tr>
                                <td><%= rent.good.goods_name %></td>
                                <td>
                                  <% days = ((rent.expire_end_date.to_i - Time.now.to_i) / 86400) %>
                                  <% if days > 0 %>
                                    <span class="label bg-green"><%= days %>日</span>
                                  <% end %>
                                  <% if days < 0 %>
                                    <span class="label bg-red">返せ</span>
                                  <% end %>
                                </td>
                                <!-- <td><% rent.expire_start_date %></td>
                                <td><% rent.expire_end_date %></td> -->
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Task Info -->
</div>